effusion_a_cappella/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
import emailsender.views
import reactloader.views

urlpatterns = [
    re_path(r'admin/?', admin.site.urls),
    path('', include('events.urls')),
    path('', include('members.urls')),
    path('', include('videos.urls')),
    path('contact', emailsender.views.send_email, name='emailsender')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + [
    path('', include('reactloader.urls'))
]

events/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/posts/', views.NewsPostListCreate.as_view(), name='posts'),
]

members/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('api/members/', views.MemberListCreate.as_view(), name='members'),
]

reactloader/urls.py
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'.*', views.react_app)
]

videos/urls.py
from django.urls import path, re_path
from . import views

urlpatterns = [
    path('api/photos/', views.MediaPhotoListCreate.as_view(), name='photos'),
    path('api/videos/', views.MediaVideoListCreate.as_view(), name='videos')
]

emailsender/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models
from datetime import date

class NewsPost(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField(default=date.today)
    body = models.TextField(default='')

    def __str__(self):
        return self.title

members/models.py
from django.db import models

IMAGE_DIR = 'images/'

class Member(models.Model):
    bio = models.TextField(default='')
    exec_position = models.CharField(max_length=200, default='', blank=True, null=True)
    name = models.CharField(max_length=200)
    part = models.CharField(max_length=200)
    src = models.ImageField(upload_to=IMAGE_DIR)
    thumbnail = models.ImageField(upload_to=IMAGE_DIR, blank=True, null=True)
    years = models.CharField(max_length=100, default='')

    def __str__(self):
        return self.name


class Alumni(models.Model):
    picture = models.ImageField(upload_to='images/')
    info = models.CharField(max_length=5000)
    year = models.CharField(max_length=100, default='')

reactloader/models.py
from django.db import models

IMAGE_DIR = 'images/'

class HomeImage(models.Model):
    caption = models.CharField(max_length=100)
    credits = models.CharField(max_length=100)
    src = models.ImageField(upload_to=IMAGE_DIR)

    def __str__(self):
        return self.src.name

videos/models.py
from django.db import models
from django.core.exceptions import ValidationError

from videos.youtubeclient import fetch_title

IMAGE_DIR = 'images/'

class MediaPhoto(models.Model):
    caption = models.CharField(max_length=100)
    src = models.ImageField(upload_to=IMAGE_DIR)

    def __str__(self):
        return self.src.name

class MediaVideo(models.Model):
    video_id = models.CharField(max_length=100)
    caption = models.CharField(max_length=100)

    def __str__(self):
        return self.caption

    def clean(self):
        if self.video_id == '':
            return # Front end form validation should reject the request.

        title = fetch_title(self.video_id)
        if title is None:
            message = f'YouTube video "{self.video_id}" could not be found.'
            raise ValidationError(message)

emailsender/forms.py
from django import forms

class EmailForm(forms.Form):
    subject = forms.CharField(label='subject', max_length=300)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

emailsender/views.py
from django.shortcuts import render
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse, HttpResponseBadRequest

import json

def nonempty(s):
    return isinstance(s, str) and len(s) > 0

def send_email(request):
    try:
        data = json.loads(request.body)
        print(data)
        if all(map(nonempty, [data['name'], data['email'], data['message']])):
            subject = f"New message from {data['name']}"
            message = f"From: {data['email']}\n\n{data['message']}"
            sender = data['email']
            recipients = settings.EMAIL_RECIPIENTS
            send_mail(subject, message, sender, recipients)
            return HttpResponse('Email sent!')
        raise ValidationError('Request validation failed')
    except (json.decoder.JSONDecodeError, ValidationError, KeyError):
        return HttpResponseBadRequest('Bad Request')

events/views.py
from django.shortcuts import render
from events.models import NewsPost
from events.serializers import NewsPostSerializer
from rest_framework import generics

class NewsPostListCreate(generics.ListCreateAPIView):
    '''
    Generic API views for the Event models
    '''
    queryset = NewsPost.objects.all()
    serializer_class = NewsPostSerializer

members/views.py
from django.shortcuts import render
from members.models import Member, Alumni
from members.serializers import MemberSerializer, AlumniSerializer
from rest_framework import generics

class MemberListCreate(generics.ListCreateAPIView):
    '''
    Generic API views for the current members models
    '''
    queryset = Member.objects.all()
    serializer_class = MemberSerializer

class AlumniListCreate(generics.ListCreateAPIView):
    '''
    Generic API views for the alumni models
    '''
    queryset = Alumni.objects.all()
    serializer_class = AlumniSerializer

reactloader/views.py
from django.shortcuts import render
from rest_framework import generics

from events.models import NewsPost
from events.serializers import NewsPostSerializer
from members.models import Member
from members.serializers import MemberSerializer
from videos.models import MediaPhoto, MediaVideo
from videos.serializers import MediaPhotoSerializer, MediaVideoSerializer
from videos.youtubeclient import fetch_title
from .models import HomeImage
from .serializers import HomeImageSerializer

import json

def react_app(request):
    home_images = [HomeImageSerializer(h).data for h in HomeImage.objects.all()]
    members = [MemberSerializer(m).data for m in Member.objects.all()]
    news = [NewsPostSerializer(n).data for n in NewsPost.objects.order_by('-date')]
    photos = [MediaPhotoSerializer(m).data for m in MediaPhoto.objects.all()]
    videos = [MediaVideoSerializer(m).data for m in MediaVideo.objects.all()]

    # Hit the YouTube API every time someone visits the home page.
    # This is an ugly hack to make sure our API key doesn't expire.
    dummy_title = fetch_title('9dH6AMVuPzE') if request.path == '/' else '' # ID of "No Air"

    effusion_params = {
        'members': members,
        'media': videos + photos,
        'homeImages': home_images,
        'news': news,
        'dummy_title': dummy_title
    }
    context = { 'effusion_params': json.dumps(effusion_params) }
    return render(request, 'index.html', context)

videos/views.py
# from django.shortcuts import render
from videos.models import MediaPhoto, MediaVideo
from videos.serializers import MediaPhotoSerializer, MediaVideoSerializer
from rest_framework import generics

import json

class MediaPhotoListCreate(generics.ListCreateAPIView):
    '''
    Generic API views for the current media photo models
    '''
    queryset = MediaPhoto.objects.all()
    serializer_class = MediaPhotoSerializer

class MediaVideoListCreate(generics.ListCreateAPIView):
    '''
    Generic API views for the current media video models
    '''
    queryset = MediaVideo.objects.all()
    serializer_class = MediaVideoSerializer

emailsender/templates/emailsender/emailsender.html
<h1>Contact Us</h1>
<form method="post">
    {%  csrf_token %}
    <p><label for="id_subject">Subject:</label>
        <input id="id_subject" type="text" name="subject" maxlength="100" required></p>
    <p><label for="id_message">Message:</label>
        <textarea name="message" id="id_message" required></textarea></p>
    <p><label for="id_sender">Sender:</label>
        <input type="email" name="sender" id="id_sender" required></p>
    <p><label for="id_cc_myself">Cc myself:</label>
        <input type="checkbox" name="cc_myself" id="id_cc_myself"></p>

    <div class="form-actions">
        <button type="submit">Send</button>
    </div>
</form>

events/templates/events/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href={% static 'style.css' %} />
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://fonts.googleapis.com/css?family=Josefin+Sans&display=swap" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Work+Sans&display=swap" rel="stylesheet">
  </head>

  <body>

      <nav class="navbar navbar-expand-sm navbar-dark bg-custom mb-3" id="navigation">
        <div class="container" id="navcontainer">
            <a class="navbar-brand" href="{% url 'home' %}"><img src={% static 'logo-cropped-transparent.png' %} id="logo" /></a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'home' %}>Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'members' %}>Members</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href={% url 'videos' %}>Media</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    {% block content %} {% endblock content %}


      <footer class="text-muted">
        <div class="container text-center"><p>© Chenzhun Huang {% now "Y" %}</p></div>
      </footer>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      // Get the current year for the copyright
      $("#year").text(new Date().getFullYear());
    </script>
  </body>
</html>

events/templates/events/events.html
{% extends 'events/base.html' %}

{% block title %}
    Events
{% endblock %}

{% block content %}
Hello
{% endblock %}

events/templates/events/home.html
{% extends 'events/base.html' %}

{% block title %}
    Home
{% endblock %}

{% block content %}
    {% load staticfiles %}
    <div id="carouselhome" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselhome" data-slide-to="0" class="active"></li>
            <li data-target="#carouselhome" data-slide-to="1"></li>
            <li data-target="#carouselhome" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src={% static 'carousel.jpg' %} alt="slide1" class="d-block w-100">
                <div class="carousel-caption d-none d-md-block bg-transparent" id="pc">
                    <h5 class="bg-transparent">ADRIFT | SPRING CONCERT</h5>
                    <p class="bg-transparent">Photo credits: Nicolas Photographie</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src={% static 'carousel2.jpg' %} alt="slide2" class="d-block w-100">
                <div class="carousel-caption d-non d-md-block bg-tranparent" id="pc">
                    <h5 class="bg-transparent">ADRIFT | SPRING CONCERT</h5>
                    <p class="bg-transparent">Photo credits: Nicolas Photographie</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src={% static 'carousel3.jpg' %} alt="slide3" class="d-block w-100">
                <div class="carousel-caption d-non d-md-block bg-transparent" id="pc">
                    <h5 class="bg-transparent">ADRIFT | SPRING CONCERT</h5>
                    <p class="bg-transparent">Photo credits: Nicolas Photographie</p>
                </div>
            </div>


        <a class="carousel-control-prev" href="#carouselhome" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>

        <a class="carousel-control-next" href="#carouselhome" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
        </div>
    </div>

    <style>
        .parallax {
          /* The image used */
          background-image: url({% static 'about.jpg' %});

          /* Set a specific height */
          min-height: 500px;

          /* Create the parallax scrolling effect */
          background-attachment: fixed;
          background-position: center;
          background-repeat: no-repeat;
          background-size: cover;
        }
    </style>

    <div class="parallax"></div>

    <div id="intro">
        <h1 class="text-center text-white">About Effusion</h1>
        <div class="container" id="about">
            <p>Formed 18 years ago in 1999, Effusion started off a small and humble group of musical geniuses who laid a foundation of soul haunting repertoire and mind-numbing good looks for future generations to build upon. 16 years, 3 CDs, and countless roadtrips later, Effusion is still laughing, good-time-ing, and making sweet a cappella.</p>

            <p>Effusion performs at events, soirees, dinners, festivals, and student functions in and around Montreal, QC. We also take time our from our busy schedules to travel around Canada and the US to collaborate and perform with other a cappella groups, bands, and musicians of all sorts.</p>
            <p>Music without instruments is our passion and we draw our influences from across the musical spectrum. R&B, soul, gospel, pop, folk, rock, and jazz influences can all be heard in our repertoire. Besides singing, Effusion has been known for many a memorable skit at end-of-semester concerts and for questionable dance skills.</p>
            <p>Want to find out more about the group? Click on to our members page or send us an email!</p>
            <p>Reviews:</p>
            <p class="text-info">“Unless you are McGill University’s Effusion, and your blend so absolutely unbelievable that you don’t need to dance around to superficially surprise an audience. Indeed, their sound was so magnificent that I’m pretty sure I stopped breathing for awhile.”<p class="text-white">– Doug Friedman [Brandeis VoiceMale]</p></p>
            <p class="text-info">“When Effusion started singing, I had trouble holding my camera straight because I just wanted to watch and enjoy…something about this group caught me off guard… You know when a person goes into a zone, they get lost in their own little world? This was like watching a group of people get lost in their own little ‘group world’.”
            <p class="text-white"> – Abid Virani [Abid Virani: In Words]</p></p>
            <p class="text-info">“It’s astonishing how a group of 16 vocalists with pitches ranging from bass to soprano and everything in between are able to perform music live completely in time with one another.”
            <p class="text-white">– Michael Gord [IX Daily]</p></p>


        </div>
    </div>

{% endblock %}

videos/templates/videos/videos.html
Videos